gatsby-config.js
just the description should be enough
=> roll our own feed without the whole content in it

content/posts/react-query-websockets/index.mdx
This PR fixes a typo I found while reading [this great post](https://tkdodo.eu/blog/using-web-sockets-with-react-query).
Thank you!
=> Fix typo in web sockets post

content/posts/practical-react-query/index.mdx
Hi @TkDodo 
I'm Yuri Tsai, a Taiwanese. I start learning React Query recently, and your articles are very impressed me! So I made a translation of Traditional Chinese in my blog.  Hope you could accept it and let more people know about it. Thank you!
=> add traditional chinese translation

content/posts/practical-react-query/index.mdx
Hi @TkDodo
I translated [Practical React Query](https://tkdodo.eu/blog/practical-react-query) into Japanese. I will be grateful if you check 😃
=> chore: added Japanese translation Practical React Query

content/posts/callback-refs/index.mdx
Hi @TkDodo,
I translated [Avoiding useEffect with callback refs](https://tkdodo.eu/blog/avoiding-use-effect-with-callback-refs) into Korean.
Please check. Thank you.
=> added korean translation

content/posts/dont-over-usestate/index.mdx
I translated your `dont-over-usestate` blog post into Korean
=> added Korean translation of dont-over-usestate

content/posts/simplifying-useeffect/index.mdx
Hello @TkDodo. Simplifying useEffect Completed the translation of the post and fixed the typo. thank you!
=> Add Korean Translation

content/posts/usestate-for-true-memoization/index.mdx
I added a Korean translation of use-state-for-one-time-initializations I have always learned a lot from you!
=> Added korean tranlation

content/posts/practical-react-query/index.mdx, content/posts/react-query-data-transformations/index.mdx, content/posts/react-query-render-optimizations/index.mdx, content/posts/status-checks-in-react-query/index.mdx
I added Spanish translations for the 4 first posts in the React query series (thanks for all your work, I've learned so much already!), hope it's ok to update them all in one PR.
I plan to keep translating this series, please let me know if you prefer a PR per post
=> add spanish translations to react-query 1 to 4 posts

content/posts/practical-react-query/index.mdx
Thanks for your blogs, I think it's very good to understand react query. And these tips are very useful, I want to translate them for more people to see.
=> practical react query add 简体中文

content/posts/seeding-query-cache/index.mdx
Added Korean Translation of `Seeding the Query Cache`.
=> Add Korean Translation to seeding-query-cache

content/posts/working-with-zustand/index.mdx
👍
https://hyunjinee.notion.site/Working-with-Zustand-73c2d6bbb53d4c6e9944ddc5e23706a1
=> docs: translate working with zustand to korean

content/posts/react-query-placeholder-and-initial-data/index.mdx
Removing an undesired apostrophe
=> Fix typo in "Placeholder and Initial Data"

content/posts/react-query-and-rr/index.mdx
reference: 
https://twitter.com/zilahy/status/1611711186046779392?s=61&t=BP4sSusArW2E7ukJjDfe9A
=> fixed file name in codeblock examples

content/posts/react-query-offline/index.mdx
I have done a Simplified Chinese version of this post.
=> add Simplified Chinese version

content/posts/callback-refs/index.mdx
I Added Japanese Translation link of callback-ref post
https://qiita.com/70ki8suda/items/831727af51c572e10ba8
=> add Japanese Translation link to callback-ref post

content/posts/callback-refs/index.mdx
I am so sorry.
I added translation to the callback ref post. But I wrote it wrong.
=> fixed typo of link url of japanese translation of callback ref post

content/posts/inside-react-query/index.mdx
I translated https://tkdodo.eu/blog/inside-react-query into Japanese.
=> add japanese translation to inside react query

content/posts/practical-react-query/index.mdx
Original Article: https://tkdodo.eu/blog/practical-react-query
Article in my blog, translated to Russian: https://garbalau-blog.vercel.app/blog/react-query-overview
Waiting for your reply, thanks!
=> Created Russian translation for React Query Article

content/posts/react-query-data-transformations/index.mdx, content/posts/react-query-render-optimizations/index.mdx
hello!
I added Japanese translate.
Thanks for the great article!
=> add ja translate 

content/posts/react-query-effective-query-keys/index.mdx
Seems like you wanted a string.
=> fix example in "effect query keys"

content/posts/why-react-isnt-dying/index.mdx
=> docs: translate why react isn't dying to korean

content/posts/api-design/index.mdx
=> fix: type 'no' to not

content/posts/api-design/index.mdx
=> translate Breaking React Query's API on purpose into Korean

content/posts/testing-react-query/index.mdx
I translated https://tkdodo.eu/blog/testing-react-query into Japanese.
=> Add japanese translation to Testing React Query

content/posts/you-might-not-need-react-query/index.mdx
Fixed a typo in the You Might Not Need React Query blog
=> Fix you-might-not-need-react-query blog typo

content/posts/you-might-not-need-react-query/index.mdx
Was a perfect post for the perfect timing. Thank you.
=> translate You Might Not Need React Query into Korean

content/posts/status-checks-in-react-query/index.mdx
Translated https://tkdodo.eu/blog/status-checks-in-react-query into Japanese.
=> Add Japanese translation for Status Checks in React Query

content/posts/thinking-in-react-query/index.mdx
I translated this great article for sharing the ideas on it with korean developers.
Always grateful for your great articles!
=> Add korean translation to thinking-in-react-query

content/posts/why-react-isnt-dying/index.mdx
I added spanish translation for "Why React isn't dying"
=> Added spanish translation

content/posts/react-query-context/index.mdx
Now I can handle implicit dependencies thanks to you!
=> add Korean translation for react-query-and-react-context

content/posts/uphill-battle-of-memoization/index.mdx
Now I'm looking forward to React Forget.
Thx always.
=> add Korean translation for uphill-battle-of-memoization

content/posts/why-you-want-react-query/index.mdx
After reading your post, I would go for React Query whenever I need to fetch some data.
=> add Korean translation of why-you-want-react-query

content/posts/refactor-impactfully/index.mdx
I translated https://tkdodo.eu/blog/refactor-impactfully into Japanese.
Thanks for the great article.
=> add japanese translation to "Refactor impactfully"

content/posts/breaking-react-querys-api-on-purpose/index.mdx
Excellent blog post, stumbled upon two things, while reading through it.
=> Spellling suggestions

content/posts/zustand-and-react-context/index.mdx
Hi. I'm Web FE engineer. I love Web open sources.
Thank you for your insightful article. So I want to add my translation in Korean.
https://velog.io/@ojj1123/zustand-and-react-context
=> Translate "Zustand and React Context" post in Korean

content/posts/mastering-mutations-in-react-query/index.mdx
I thought this would be a useful update to not confuse the reader. I understand of course that you might want to word things differently. Anyway, thanks for a great blog, I'm reading it from the start!
=> Add aside about useQuery callbacks being removed

content/posts/leveraging-the-query-function-context/index.mdx
The previous one is no longer available
=> Set up correct link to eslint-plugin-query inside tanstack query docs

content/posts/automatic-query-invalidation-after-mutations/index.mdx
I translated this article for sharing the ideas on it with korean developers.
Always grateful for your great articles!
=> Add translation of KR to automatic-query-invalidation-after-mutations

content/posts/react-19-and-suspense-a-drama-in-3-acts/index.mdx
=> add Korean translation of React 19 and Suspense - A Drama in 3 Acts

content/posts/automatic-query-invalidation-after-mutations/index.mdx
I translated this article for sharing the ideas on it with China developers.
Always grateful for your great articles!
=> Add translation of Chinese to automatic-query-invalidation-after-mutations

content/posts/react-query-fa-qs/index.mdx
=> Chore: Fix typo.

content/posts/inside-react-query/index.mdx
Hi, this link didn't work anymore so I replaced it with a new one
=> Fix persisters link in inside-react-query post

content/posts/how-infinite-queries-work/index.mdx
It was very helpful in understanding how Infinite Queries work. Thank you!
=> add Korean translation of "How Infinite Queries work"

content/posts/the-query-options-api/index.mdx
Parentheses in readable text were not closed
=> Closed parentheses

content/posts/ref-callbacks-react-19-and-the-compiler/index.mdx
Thank you for sharing your insights. I’m learning a lot thanks to you!
=> add korean translation for "Ref Callbacks, React 19 and the Compiler"

content/posts/practical-react-query/index.mdx
practical-react-query-polish-translation: add Polish translation and fix some typos
=> practical-react-query-polish-translation: add Polish translation

content/posts/introducing-x-state-store/index.mdx
Thank you for sharing your insights. I’m learning a lot thanks to you!
=> add korean translation for "Introducing XState Store"

content/posts/concurrent-optimistic-updates-in-react-query/index.mdx
Just one line for solving that difficult edge case? Awesome!
=> add Korean translation for "Concurrent Optimistic Updates in React Query"

content/posts/the-beauty-of-tan-stack-router/index.mdx
Thank you for the insightful post — it was a pleasure translating it!
=> add korean translation for "The Beauty of TanStack Router"

content/posts/the-useless-use-callback/index.mdx
I’ve been thinking a lot lately about when it’s actually appropriate to use useCallback and useMemo, and your post really helped clarify things for me. 
Thanks to you, I also learned about the existence of useEffectEvent, which I hadn’t come across before.
=> add korean translation for "The useless useCallback"

content/posts/the-uphill-battle-of-memoization/index.mdx
Learned a lot by doing this translation, thanks for sharing your knowledge! =] 
I'll be working on the next one "The Useless useCallback".
=> docs: add Brazilian Portuguese translation for the "The Uphill Battle of Memoization" article

content/posts/the-useless-use-callback/index.mdx
Thanks for sharing your knowledge through this amazing post.
@oaraujocesar I saw in #349 that you're working on this post as well, if you'd like to [contribute on my translation](https://github.com/guivictorr/guilhermevictor.me/blob/main/content/writing/the-useless-usecallback.mdx) feel free to do so 😊.
=> feat: add pt-br translation for the-useless-use-callback post

content/posts/deriving-client-state-from-server-state/index.mdx
Thank you for a nice blog post as usual!
=> Fix incorrect variable name
