- content/posts/things-to-know-about-use-state/index.mdx
Thanks much for this post!
Noticed this small change while reading and figured I'd forward it along.
> Correct typo: `perviousValue` -> `previousValue`

- content/posts/practical-react-query/index.mdx
Fixed typo by changing the word `quey` to `query`
> changed "quey" to "query"

- content/posts/usestate-vs-usereducer/index.mdx
great post, thanks for your great work! I just wanted to fix you dumb-reducer action object to match your action object used in the render function. { type, value } instead of { payload, value } :)
> fix: code typo

- netlify.toml
when you go to tkdodo.eu, we make requests to tkdodo.eu/images for the premium sponsors; this kinda happens before the request to /blog, so those are invalid requests; redirecting those requests to /blog/images seems right
> redirect image requests

- content/posts/why-i-dont-like-reduce/index.mdx
eslint-plugin-unicorn has named the rule `no-reduce` as `no-array-reduce`.
> fix: no-reduce link to no-array-reduce

- content/posts/testing-react-query/index.mdx
The end of the block requires a ')' to close the 'test('
> fix: missing closing parentheses in code snippet

- content/posts/dont-over-usestate/index.mdx
- content/posts/react-query-render-optimizations/index.mdx
- content/posts/why-i-dont-like-reduce/index.mdx
Seems reacttraining.com website had changed their routing slightly. This should help.
> fix: links to reacttraining post

- content/posts/react-query-state-management/index.mdx
I translated https://tkdodo.eu/blog/react-query-as-a-state-manager into Japanese.
> add Japanese translation to react query as a state manager

- content/posts/practical-react-query/index.mdx
- content/posts/react-query-data-transformations/index.mdx
- content/posts/react-query-effective-query-keys/index.mdx
- content/posts/react-query-error-handling/index.mdx
- content/posts/react-query-forms/index.mdx
- content/posts/react-query-leveraging-query-context/index.mdx
- content/posts/react-query-mutations/index.mdx
- content/posts/react-query-offline/index.mdx
- content/posts/react-query-placeholder-and-initial-data/index.mdx
- content/posts/react-query-render-optimizations/index.mdx
- content/posts/react-query-state-management/index.mdx
- content/posts/react-query-typescript/index.mdx
- content/posts/react-query-websockets/index.mdx
- content/posts/status-checks-in-react-query/index.mdx
- content/posts/testing-react-query/index.mdx
Hello, @TkDodo! The blog domain with the Korean translation has expired, so `parang.tech` It changed to `parang.gatsbyjs.io`.
I am sending you a PR by modifying the link to the Korean translation part. I'm always reading it thankfully!❤️
> fix: react-query korean translations link

- content/posts/inside-react-query/index.mdx
I translate [Inside React Query](https://tkdodo.eu/blog/inside-react-query) into Korean.
https://velog.io/@hyunjine/Inside-React-Query
> docs: translate inside react query to korean

- content/posts/array-types-in-typescript/index.mdx
I've become hyper-aware of the spacing inconsistencies in your latest blog post, so here's a quick pass on it to fix it 🤪
Feel free to dismiss the PR if you don't think it's necessary and have a good weekend 😉
> chore(array-types-in-typescript): fix whitespace inconsistencies

- content/posts/array-types-in-typescript/index.mdx
Continue work done in https://github.com/TkDodo/blog/pull/226
> Fix spaces in "Array Types in TypeScript"

- content/posts/uphill-battle-of-memoization/index.mdx
The slow tables example currently does not even access the state, maybe it would be better to access the state?
> feat: align tables slow example better with zustand solution

- src/@lekoarts/gatsby-theme-minimal-blog/components/listing.tsx
Switching themes on your blog has a minor "flicker" on cards borders due to CSS transitions which don't seem to be applied on borders, just making it transparent seems to fix it and it can't be removed entirely because of hovers
Sorry for nit picking, just some ocd. And thanks for your amazing work for the community!
> card border flicker on theme switch

- src/components/MonoLisa.tsx
- src/components/PremiumSponsors.tsx
- src/components/Sponsors.tsx
👋 Just noticed the url to the `mono lisa` font was broken when I tried accessing it from your blog, because it's missing a protocol part so it resolves to a relative path.
> fix: add missing protocol in mono lisa links

- content/posts/effective-react-query-keys/index.mdx
- content/posts/practical-react-query/index.mdx
- content/posts/react-query-and-type-script/index.mdx
- content/posts/react-query-data-transformations/index.mdx
- content/posts/react-query-render-optimizations/index.mdx
- content/posts/status-checks-in-react-query/index.mdx
- content/posts/testing-react-query/index.mdx
- content/posts/using-web-sockets-with-react-query/index.mdx
It seems the Korean translation link for some of the React Query posts is not functioning correctly. I've been trying to find out how to contact the translator, but I can't find a way to do so. 
Therefore, I created a new pull request for asking you to modify the links on the Korean translation page.
> Modify korean translation link of your react-query posts

- content/posts/why-you-want-react-query/index.mdx
Each code sample in sections 1-5 is missing the closing paren for the .then call, and the functions passed in are missing the closing curly brace. This just adds a line in for each block to properly close them.
> Properly close .then calls in each section

- content/posts/mastering-mutations-in-react-query/index.mdx
- content/posts/offline-react-query/index.mdx
- content/posts/react-query-and-forms/index.mdx
Hello, I've created a pull request to request modifications to the links in the Korean translation documents for the following pages:
https://tkdodo.eu/blog/mastering-mutations-in-react-query
https://tkdodo.eu/blog/offline-react-query
https://tkdodo.eu/blog/react-query-and-forms
> modify korean translation link of react-query posts

- content/posts/react-19-and-suspense-a-drama-in-3-acts/index.mdx
```jsx
<Suspense fallback={fallback={<p>...</p>}}>
```
Remove the inner `fallback={}`
> chore: fix typo

- content/posts/introducing-x-state-store/index.mdx
I really enjoyed your article about xstate's new store library and noticed a minor typo fixed here
creatStore => createStore
> content: fix typo in introducing-x-state-store

- content/posts/react-query-meets-react-router/index.mdx
Update link to react-router example in tanstack-query docs.
Reason: current link is for an older version of the docs and is broken leading to a 404.
> Update react-query-meets-react-router - index.mdx

- content/posts/2021-in-review/index.mdx
- content/posts/2022-in-review/index.mdx
- content/posts/putting-props-to-use-state/index.mdx
- content/posts/simplifying-use-effect/index.mdx
Further to https://github.com/TkDodo/blog/pull/317, I've updated the following Twitter links to the owners BlueSky accounts.
In each case:
- The person has an active [BlueSky](https://bsky.app) account
- The person has declared publicly that they are using BlueSky primarily over X/Twitter
There are some other twitter links possibly eligible for replacement but I've limited to very public declarations disowning X for this first pass.
List of moved accounts:
- Mark Ericson 
- https://twitter.com/acemarke -> https://bsky.app/profile/acemarke.dev
- https://x.com/acemarke/status/1860512437251735784
- Dan Abramov
- https://twitter.com/dan_abramov - https://bsky.app/profile/danabra.mov
- twitter account is dead (he was shadowbanned at one point accourding to https://youtu.be/F1sJW6nTP6E?t=720)
- …
> External bsky links pass 1

- content/posts/dont-over-use-state/index.mdx
- content/posts/refs-events-and-escape-hatches/index.mdx
- content/posts/the-query-options-api/index.mdx
This is a continuation of https://github.com/TkDodo/blog/pull/320
In this case it's slightly more awkward. In this case, as before:
- The person has an active [BlueSky](https://bsky.app/) account
- The person has declared publicly that they are using BlueSky primarily over X/Twitter
But the links in this case ARE associated with a direct link to X via the `Tweet` component in same post as the link. In the case of R. Alex it's actually a dead link as the account is protected. 
This comprises what are the last of the easy migrations imo. Every other link is still active enough and doesn't have the same declarations. Hopefully Bluesky lasts forever and we don't have to do this again lol.
- Haz‬
- https://twitter.com/diegohaz -> https://bsky.app/profile/haz.dev
- …
> External bksy links pass 2

- content/posts/ref-callbacks-react-19-and-the-compiler/index.mdx
Tiny update so that the name of the function in the text matches the name of the function in code.
> Correct function name in text

- content/posts/automatic-query-invalidation-after-mutations/index.mdx
Translated https://tkdodo.eu/blog/automatic-query-invalidation-after-mutations into Japanese.
> add japanese translation to "Automatic Query Invalidation after Mutations"

- content/posts/putting-props-to-use-state/index.mdx
- Updated the outdated link to "think in hooks"
**From:** [https://wattenberger.com/blog/react-hooks](https://wattenberger.com/blog/react-hooks)  
**To:** [https://2019.wattenberger.com/blog/react-hooks](https://2019.wattenberger.com/blog/react-hooks)
The previous link was no longer accessible, leading to a **404 page**. This update ensures that readers can still access the original article.
> fix: update broken external link in putting-props-to-useState post

- content/posts/leveraging-the-query-function-context/index.mdx
The Korean translation link of [`Leveraging the Query Function Context`](https://parang.gatsbyjs.io/react/2022-react-09/) is broken, so I was considering translating it, but I found that the #252 contributor had already translated it, so I only fixed the connection link.
I'm enjoying reading your posts. Thank you.
> Fix broken korean translation link of "Leveraging the Query Function Context"

- content/posts/react-query-api-design-lessons-learned/index.mdx
**Live URL**  
[[번역] React Query API 디자인, 그 교훈](https://velog.io/@willy4202/%EB%B2%88%EC%97%AD-React-Query-API-%EB%94%94%EC%9E%90%EC%9D%B8-%EA%B7%B8-%EA%B5%90%ED%9B%88)
This PR adds a link to the Korean translation of the article **“React Query API Design – Lessons Learned.”**
At the very beginning of the translation I included the required notice:
> 🇰🇷 This article is a Korean translation of the original post “React Query API Design – Lessons Learned.”  
> Original: <https://tkdodo.eu/blog/react-query-api-design-lessons-learned>
**Translator:** Willy4202
> docs(ko): add korean translation link for react-query api desgin lesson learned

- content/posts/deriving-client-state-from-server-state/index.mdx
Added a Korean translation for the article "Deriving Client State from Server State".
This PR adds the Korean translation of Kent C. Dodds’ article on deriving client state from server state, providing Korean readers with the full explanation and examples in their native language.
> docs: add korean translation for 'deriving-client-state-from-server-state
